language: android
#### use android since there are android components####
jdk:
  - openjdk11

android:
  components:
    - build-tools-26.0.2
    - android-26
    - extra

licenses:
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  - 'android-sdk-preview-license-.+'


install: true

sudo: required
before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean build -i --continue

