language: android
#### use android since there are android components####
jdk:
  - openjdk11
os: linux
dist: trusty


android:
  components:
    - build-tools-29
    - android-29
    - extra
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-preview-license-52d11cd2'

install: true


before_script:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "platforms;android-29"

script:
  - ./gradlew clean build -i --continue

